### ISSUE TITLE
選挙トリビアWiki

### ISSUE THREAD

**Issue by nissy813** [codeforsetagaya/hub#14]
# 選挙トリビアWiki
## 背景・経緯

Code for Setagaya 12月号（衆議院選データ分析）では、身近に行われているはずの選挙について、トリビア級の驚く事実を沢山知ることができました。

そんな選挙のトリビアの源泉は「公職選挙法」になるのですが、ここから市民として知っておくべき事項を、選挙トリビアとして可視化し、選挙行動に活かせる環境を作ることが重要であると考えました。

みんなで力を合わせて選挙ルールの見える化を進め、より賢く選挙行動していける市民の土壌を作りましょう！
## ToDo
- [x] トリビア記載環境構築（Wiki準備）
- [x] トリビア初版の作成（12月号の内容反映）
- [x] 内容チェック＆微修正
- [x] トリビア公開（以降はWikiスタイルで、みんなで自由に追記していく）
## 執筆環境

[選挙トリビアWiki](https://github.com/codeforsetagaya/hub/wiki/%E9%81%B8%E6%8C%99%E3%83%88%E3%83%AA%E3%83%93%E3%82%A2Wiki)
## 参考情報

[公職選挙法：http://law.e-gov.go.jp/htmldata/S25/S25HO100.html](http://law.e-gov.go.jp/htmldata/S25/S25HO100.html)

**Comment by cognitom** [comment]
:+1:

**Comment by nissy813** [comment]
執筆環境に、選挙トリビアWikiを追加

**Comment by nissy813** [comment]
Wiki環境はあるのでDone

**Comment by nissy813** [comment]
出来れば１月中にリリースしたいですね。

**Comment by nissy813** [comment]
修正完了

**Comment by cognitom** [comment]
お、かなり細かいところまで。すばらしい!

**Comment by nissy813** [comment]
これでDoneです。
