### ISSUE TITLE
世田谷区の選挙関連の情報を返すAPIがほしい

### ISSUE THREAD

**Issue by cognitom** [codeforsetagaya/hub#7]
とりあえず、このあたりの得票データなど。
- [x] 世田谷区長選挙 2011年
- [x] 世田谷区議会議員選挙 2011年
- [x] 衆議院議員総選挙 東京都第5区 2014年
- [x] 衆議院議員総選挙 東京都第6区 2014年
- [ ] 世田谷区長選挙 2015年
- [ ] 世田谷区議会議員選挙 2015年

下記、取得したい内容。
- [x] 候補者名
- [x] 政党名
- [x] 得票数
- [x] 当選 or 落選
- [ ] 世代別得票数
- [ ] 男女別得票数

**Comment by cognitom** [comment]
現時点で公開されているものについては、完了しました。また、次回の統一選が始まったら、Issueを再度オープンしましょう。

**Comment by nissy813** [comment]
:+1:
